defmodule SsTest.Elements.Phoneme do
    # This turns this module into a resource
    use Ash.Resource, domain: SsTest.SoundSpelling

    actions do
      # Use the default implementation of the :read action
      defaults [:read]

      # and a create action, which we'll customize later
      create :create do
        accept [:sound]
      end
    end

    # Attributes are the simple pieces of data that exist on your resource
    attributes do
      # Add an autogenerated UUID primary key called `:id`.
      uuid_primary_key :id

      # Add a string type attribute called `:subject`
      attribute :sound, :string do
        allow_nil? false
        public? true
      end
    end

end
