defmodule SsTest.Concepts.ReadSound do
  use Ash.Resource, domain: SsTest.SoundSpelling
  #   data_layer: your_data_layer

  # postgres do
  #   table "tweet_hashtags"
  #   repo MyApp.Repo
  # end

  relationships do
    belongs_to :grapheme, SsTest.Elements.Grapheme, primary_key?: true, allow_nil?: false
    belongs_to :phoneme, SsTest.Elements.Phoneme, primary_key?: true, allow_nil?: false
  end

  actions do
    defaults [:read, :destroy, create: :*, update: :*]
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :name, :string do
      allow_nil? true
      public? true
    end
  end
end
