defmodule SsTest.Concepts.ReadSound do
  # , data_layer: Ash.DataLayer.Ets
  use Ash.Resource, domain: SsTest.SoundSpelling, data_layer: Ash.DataLayer.Ets
  #   data_layer: your_data_layer

  # postgres do
  #   table "tweet_hashtags"
  #   repo MyApp.Repo
  # end

  relationships do
    belongs_to :grapheme, SsTest.Elements.Grapheme, primary_key?: true, allow_nil?: false
    belongs_to :phoneme, SsTest.Elements.Phoneme, primary_key?: true, allow_nil?: false
  end

  actions do
    defaults [:read, :destroy, :create]

    # create :create do
    #   accept [:grapheme, :phoneme]
    # end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :name, :string do
      allow_nil? true
      public? true
    end
  end

  code_interface do
    # define_for(SsTest.Elements)
    define :create
    define :read
    define :by_phoneme, get_by: [:phoneme], action: :read
    define :by_grapheme, get_by: [:grapheme], action: :read
  end
end
